### ISSUE TITLE
Optional twig extensions

### ISSUE THREAD

**Issue by aserratorta** [aserratorta/SymfonyTraining#23]
Hi David!
This commit shows this mistake. I'm thinking it's caused because there isn’t any USE statement in SymfonyExtension.php.                                                       eba6f5b
![screenshot - 041015 - 01 08 03](https://cloud.githubusercontent.com/assets/12971681/10323385/fb9f1d12-6c82-11e5-95a1-47bcb3bf61da.png)

**Comment by davidromani** [comment]
After pull this commit https://github.com/aserratorta/SymfonyTraining/commit/5838a1bb5f1d560f5e58aab544963c3ea01c44b5 remember to execute

```
composer install
```

command to apply composer.json changes.

This commit removes some unused files, avoid to define services inside config.yml (use services.yml instead to keep things well organised).

Finally, for now I've only enabled Twig_Extensions_Extension_Text service because you need the _truncate_ filter inside offer.html.twig view. The other Twig extensions are disabled to fix this issue, but probably you will need to enable soon.

**Comment by aserratorta** [comment]
This is very specific!!!

**Comment by aserratorta** [comment]
Is there any problem?

![screenshot - 041015 - 01 08 03](https://cloud.githubusercontent.com/assets/12971681/10339527/14001d32-6d0c-11e5-9cf8-45acfe8774c1.png)

The site gets render.

**Comment by davidromani** [comment]
Yes. Apache is the owner of your cache files stored inside app/cache directory, so you can't delete this files with cache:clear command because you don't have enough permissions.

Read section "Cómo solucionar este problema en Linux" here http://symfony.es/documentacion/como-solucionar-el-problema-de-los-permisos-de-symfony2/

**Comment by aserratorta** [comment]
afe6d02
I had to fix it following "si algo falla" section.
But I needed another section called "si falla si algo falla" because my web/app.php didn't have:
 _// If you don't want to setup permissions the proper way, just uncomment the following PHP line
// read http://symfony.com/doc/current/book/installation.html#configuration-and-setup for more information
//umask(0000);_
So I copied from php_dev.php file.

I hope it works well.

![screenshot - 041015 - 01 08 03](https://cloud.githubusercontent.com/assets/12971681/10370822/f0bb427c-6de0-11e5-9359-008c34070388.png)

I think so...
